[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "amazonmart"
username = "postgres"
password = "Hephzibah@1414"

# [postgres]
# host = "localhost"
# port = 5432
# dbname = "amazonmart"
# user = "postgres"
# password = "Hephzibah@1414"
